version: '3'

services:
  node0:
    build:
      context: .
      dockerfile: docker/nodes.Dockerfile
      network: host
    image: node-image
    profiles: [ "node" ]
    ports:
      - "8080:8080"
    environment:
      SVC_PORT: "8080"
      GIN_MODE: "release"
    networks:
      - node
  node1:
    image: node-image
    depends_on:
      - node0
    profiles: [ "node" ]
    ports:
      - "8081:8081"
    environment:
      SVC_PORT: "8081"
      GIN_MODE: "release"
    networks:
      - node
  node2:
    image: node-image
    depends_on:
      - node0
    profiles: [ "node" ]
    ports:
      - "8082:8082"
    environment:
      SVC_PORT: "8082"
      GIN_MODE: "release"
    networks:
      - node
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    profiles: [ "client" ]

networks:
  node: