version: '3'

services:
  node0:
    build:
      context: .
      dockerfile: docker/nodes.Dockerfile
      network: host
    image: node-image
    profiles: [ "backend" ]
    ports:
      - "8080:8080"
    environment:
      SVC_PORT: "8080"
      GIN_MODE: "release"
    networks:
      - node
  node1:
    image: node-image
    depends_on:
      - node0
    profiles: [ "backend" ]
    ports:
      - "8081:8081"
    environment:
      SVC_PORT: "8081"
      GIN_MODE: "release"
    networks:
      - node
  node2:
    image: node-image
    depends_on:
      - node0
    profiles: [ "backend" ]
    ports:
      - "8082:8082"
    environment:
      SVC_PORT: "8082"
      GIN_MODE: "release"
    networks:
      - node
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
      network: host
    profiles: [ "client" ]
    environment:
      SVC_HOSTS: "http://host.docker.internal:8080,http://host.docker.internal:8081,http://host.docker.internal:8082"
      SVC_N: "1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  node: